array(
  array(
    'nid' => '13',
    'type' => 'news',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1287662124',
    'changed' => '1287662124',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '13',
    'revision_uid' => '1',
    'title' => 'New Drupal Training Dates Announced!',
    'body' => '<img src=\"/files/users/154/Badge_training_partner.png\" width=\"200\" height=\"90\" alt=\"expert drupal training courses & classes\" />

After a successful first round of Drupal training courses, we are pleased to announce new dates for our Acquia Drupal training series, as well as the official launch of a brand new course, the D.I.Y. Web Success Workshop.

But first, hear what participants Joy Hays and Michael Nelson had to say about their training experiences:

\"The training helped me to see what I was missing and gave me some new
ideas.\" - Michael Nelson

\"This training opened my eyes to how much there really is in Drupal. It\'s not just a CMS, but something that really can be used in so many different ways.\"
- Joy Hays

Reserve your seat today!

<strong>If you register by Friday, 8/13 at 12 am CST, you can use the special discount code EARLYBIRD to receive 10% off your order</strong>

<a href=\"http://www.leveltendesign.com/event/diy-web-success-workshop\"><h2><strong>New</strong>: D.I.Y. Web Success Workshop</h2></a>

<strong>September 9 & 10, 2010</strong>

Our D.I.Y. Web Success Workshop will provide a solid introduction to successful online strategies, website building, content management, and search engine  optimization.  During the two day course, participants will build a website
with an events calendar, news room, FAQ page, blog, forum, contact form and landing pages.  They will also learn how to change the theme of their website and optimize the content for search engines.  Participants will leave the class with a fully functional search friendly website for a business or organization.

<a href=\"http://www.leveltendesign.com/event/diy-web-success-workshop\">See full course description</a>

<a href=\"http://www.leveltendesign.com/event/drupal-day-9-13-10\"><h2>Drupal in a Day</h2></a>

<strong>September 13, 2010</strong>

Drupal in a Day is an overview training course designed to show you how to create your own Drupal site from start to finish.  You’ll begin the course with a blank website.  From there, you’ll add custom content and learn how to
manage that content.  You’ll also create custom content types, look at views to display content throughout your Drupal website, including creating custom blocks and custom list pages such as a blogroll or a list of recent images added to the site.

<a href=\"http://www.leveltendesign.com/event/drupal-day-9-13-10\">See full course description</a>

<a href=\"http://www.leveltendesign.com/event/drupal-site-builders-workshop\"><h2>Beginning Drupal for Site Builders</h2></a>

<strong>September 14 & 15, 2010</strong>

In two days, you’ll be brought up to speed on Drupal site building, and you’ll be ready to tackle your own project.  This Drupal training course is designed for those who have some basic familiarity with the system but want to broaden their knowledge.  Beginning Drupal for Site Builders provides deep discussions on Drupal’s installation process, as well as managing users, comments, and content.  You’ll also become familiar with Drupal’s block system, and how to use taxonomy to organize your content.

<a href=\"http://www.leveltendesign.com/event/drupal-site-builders-workshop\">See full course description</a>',
    'teaser' => '<img src=\"/files/users/154/Badge_training_partner.png\" width=\"200\" height=\"90\" alt=\"expert drupal training courses & classes\" />

After a successful first round of Drupal training courses, we are pleased to announce new dates for our Acquia Drupal training series, as well as the official launch of a brand new course, the D.I.Y. Web Success Workshop.

But first, hear what participants Joy Hays and Michael Nelson had to say about their training experiences:

\"The training helped me to see what I was missing and gave me some new
ideas.\" - Michael Nelson

',
    'log' => '',
    'revision_timestamp' => '1287662124',
    'format' => '1',
    'name' => 'admin',
    'picture' => '',
    'data' => 'a:0:{}',
    'path' => 'news/new-drupal-training-dates-announced',
    'field_news_post_date' => array(
      '0' => array(
        'value' => '2010-10-21T11:54:00',
        'timezone' => 'UTC',
        'timezone_db' => 'UTC',
        'date_type' => 'date',
      ),
    ),
    'last_comment_timestamp' => '1287662124',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(
      'tags' => array(
        '1' => 'austin, dallas, dates, drupal, houston, levelten, training',
      ),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
  array(
    'nid' => '11',
    'type' => 'news',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1287661688',
    'changed' => '1287661688',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '11',
    'revision_uid' => '1',
    'title' => 'LevelTen Wins W3 Award for Work on Caris Life Sciences',
    'body' => '<div style=\"float: left; margin: 1em .5em 1em 0em;\"><img src=\"/files/w3winner_silver_blk.gif\" width=\"113\" height=\"113\" alt=\"w3 silver award winner\" title=\"w3 2010 silver award winner\" /></div>  It is with great pleasure that I announce a recent win for the team at LevelTen.  We were informed today that we have officially won a silver W3 award for our design work on <a href=\"http://www.carislifesciences.com/\">Caris Life Sciences</a>!  For those keeping score, this marks LevelTen\'s 3rd W3 win in the last four years.

<h2>About the W3 Award</h2>

The W3 Award, judged by the <a href=\"http://www.iavisarts.org\">International Academy of the Visual Arts</a>, seeks to honor creative excellence on the web, and to recognize the creative and marketing professionals behind the webs top websites, web video, and online marketing.  According to the W3\'s website, they are \"the first major Web competition to be accessible to the biggest agencies, the smallest firms, and everyone in between.\"  For more information on the W3 awards, feel free to <a href=\"http://www.w3award.com\">check out their website</a>.

<h2>About the Caris Life Sciences Project</h2>

<blockquote>
LevelTen worked with the team at Caris Life Sciences to create a professional and engaging website on the Drupal platform. LevelTen applied their decade of web knowledge into a series of strategic wireframes before moving into the site building process. In less than a month, LevelTen went from approved design comps and wireframes to a fully approved Drupal website.

The theme is based on the 960 Grid system and uses CSS styling for all page layouts. In addition, LevelTen incorporated Features and Context functionality into the site, making it easier to manage and control website features and contextual layouts. With these tools, LevelTen created sections of the website that served multiple target audiences, as well as areas for dynamic, regularly updated content.
</blockquote>

<a href=\"http://www.leveltendesign.com/portfolio/success-story/caris-life-sciences-website-redesign-url-migration\">Read the full case study here</a>.
',
    'teaser' => '<div style=\"float: left; margin: 1em .5em 1em 0em;\"><img src=\"/files/w3winner_silver_blk.gif\" width=\"113\" height=\"113\" alt=\"w3 silver award winner\" title=\"w3 2010 silver award winner\" /></div>  It is with great pleasure that I announce a recent win for the team at LevelTen.  We were informed today that we have officially won a silver W3 award for our design work on <a href=\"http://www.carislifesciences.com/\">Caris Life Sciences</a>!  For those keeping score, this marks LevelTen\'s 3rd W3 win in the last four years.

<h2>About the W3 Award</h2>

',
    'log' => '',
    'revision_timestamp' => '1287661688',
    'format' => '1',
    'name' => 'admin',
    'picture' => '',
    'data' => 'a:0:{}',
    'path' => 'news/levelten-wins-w3-award-work-caris-life-sciences',
    'field_news_post_date' => array(
      '0' => array(
        'value' => '2010-10-21T11:47:00',
        'timezone' => 'UTC',
        'timezone_db' => 'UTC',
        'date_type' => 'date',
      ),
    ),
    'last_comment_timestamp' => '1287661688',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(
      'tags' => array(
        '1' => '2010, award, caris, w3, win',
      ),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)