array(
  array(
    'nid' => '12',
    'type' => 'blog',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1287661906',
    'changed' => '1287661906',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '12',
    'revision_uid' => '1',
    'title' => 'Six Secrets for Smarter Keyword Research',
    'body' => '<div style=\"float: left; margin: 1em .5em 1em 0em;\"><img src=\"/files/3710032217_5028b24e4e_m_0.jpeg\" width=\"240\" height=\"160\" alt=\"3710032217_5028b24e4e_m_0.jpeg\" /></div>Keyword research, one of the most essential facets of good search engine optimization can also be one of the easiest tasks to do wrong.  Here are five ways you can improve the effectiveness of your keyword research.  Then, I\'ll show you <a href=\"#easy-button\">Drupal\'s \"easy button\"</a> for better keyword research.

<h2>1.  Analyze your content for keyword ideas</h2>

One of the primary objectives for the search engines is to serve the most relevant content for a particular users query.  Search engines determine what web content is about through a variety of factors (this is what we spend time optimizing in SEO), some of these factors include your meta page titles, keyword usage within your page copy, and backlinks to your website.  So it would make sense that you would want to begin your keyword research by first figuring out what keywords and concepts are already prevalent on your webpage.

You can do this in two ways.  You could go through your content by hand, and pick out what you believe to be the most relevant or most used keywords on the page.  Or, you can put it in the hands of web software that can make this analysis for you.  In Drupal, both the <a href=\"http://drupal.org/project/alchemy\">Alchemy module</a> and <a href=\"http://drupal.org/project/scribeseo\">Scribe SEO module</a> can help you with this analysis.  Alternatively, you can try the <a href=\"http://www.leveltendesign.com/tools/contentanalysis/analyzer/scribeseo/drupal/nodeedit\">Scribe SEO module demo</a>, and input your own content to analyze.

Once you find your keyword ideas, plug them into a keyword research tool like <a href=\"http://www.wordtracker.com/\">Wordtracker</a> to get more related keywords.

<h2>2.  Start broad</h2>

When you\'re first starting keyword research, you always want to begin with broad (root) keywords, then work your way to long tail variations.  For example, if your website is an e-commerce retailer for custom bicycle seats, you may want to start your keyword research with phrases like \"bike\", \"bicycle\", or \"bike seats\".

<h2>3.  Use long tail modifiers</h2>

As you do your keyword research, you\'ll start to see variations of your primary (root) keyword pop up.  For example, your search for the phrase \"bicycle\" might return results for \"used bicycle for sale\" or \"buy bicycles online\".  \"Used\", \"for sale\", \"buy\", and \"online\" would all be considered modifier keywords, and the entire phrase (used bicycle for sale) is what we would consider a long tail keyword.  A long tail keyword by itself provides less traffic then your root keywords (bicycle), but in aggregate, there are many more relevant long tail searches then there are for your root keywords.  Long tail keywords tend to bring more qualified traffic, convert at higher rates, and are less competitive.

<h2>4.  Look at your competitors for inspiration</h2>

Use your competitors as a guide for your keyword research efforts.  Look at their meta page title tags, headers, and page copy to see what they may be trying to optimize for.  Sometimes this can even lead to inspiration for a new niche market to go after.

<h2>5.  Look for uncompetitive niches</h2>

One of the biggest mistakes people make in keyword research is assuming it\'s about finding the words with the most possible searches.  Really, good keyword research is about finding those keywords that not only get a large volume of searches, but are also uncompetitive, and deliver qualified traffic.  I frequently tell clients that I\'d rather they get 500 qualified visitors per month who convert, then 5,000 who don\'t.

<h2>6.  Localize your keywords where possible</h2>

One of the easiest ways to long tail your target keywords is to add local modifiers to them.  For example, instead of optimizing just for the phrase \"website design company\", we can add the \"Dallas\" to the phrase, making \"website design company dallas\", and be optimized for local searches as well.
<a name=\"easy-button\"></a>
<h2>The Drupal Easy Button!</h2>
As promised, here\'s the easy button for keyword research in your Drupal website.  Our Keyword Research module will help you easily perform keyword research right within the page you\'re trying to optimize.  Be sure to combine it with the other modules found in the <a href=\"http://drupal.org/project/contentanalysis\">content analysis suite</a> to unlock the true power of the <a href=\"http://drupal.org/project/kwresearch\">keyword research module</a>.

<object width=\"640\" height=\"385\"><param name=\"movie\" value=\"http://www.youtube.com/v/d_ZsnNgMeyE?fs=1&amp;hl=en_US&amp;hd=1\"></param><param name=\"allowFullScreen\" value=\"true\"></param><param name=\"allowscriptaccess\" value=\"always\"></param><embed src=\"http://www.youtube.com/v/d_ZsnNgMeyE?fs=1&amp;hl=en_US&amp;hd=1\" type=\"application/x-shockwave-flash\" allowscriptaccess=\"always\" allowfullscreen=\"true\" width=\"640\" height=\"385\"></embed></object>

<a href=\"http://www.flickr.com/photos/zitona/3710032217/sizes/m/\">Photo Credit</a>',
    'teaser' => '<div style=\"float: left; margin: 1em .5em 1em 0em;\"><img src=\"/files/3710032217_5028b24e4e_m_0.jpeg\" width=\"240\" height=\"160\" alt=\"3710032217_5028b24e4e_m_0.jpeg\" /></div>Keyword research, one of the most essential facets of good search engine optimization can also be one of the easiest tasks to do wrong.  Here are five ways you can improve the effectiveness of your keyword research.  Then, I\'ll show you <a href=\"#easy-button\">Drupal\'s \"easy button\"</a> for better keyword research.

<h2>1.  Analyze your content for keyword ideas</h2>

',
    'log' => '',
    'revision_timestamp' => '1287661906',
    'format' => '1',
    'name' => 'admin',
    'picture' => '',
    'data' => 'a:0:{}',
    'path' => 'blog/six-secrets-smarter-keyword-research',
    'last_comment_timestamp' => '1287661906',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(
      'tags' => array(
        '1' => 'drupal, drupal seo, keyword research, module, Search Engine Optimization, theory',
      ),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
  array(
    'nid' => '9',
    'type' => 'blog',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1287661473',
    'changed' => '1287661756',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '9',
    'revision_uid' => '1',
    'title' => 'How to Create a QR Code for Your Website in 5 Simple Steps',
    'body' => '<img src=\"/files/users/2418/leveltenqr2.PNG\" width=\"244\" height=\"248\" alt=\"leveltenqr2.PNG\" />
I am super stoked about being able to create QR codes for my website. To scan the code you must have a <a href=\"http://itunes.apple.com/us/app/quickmark-qr-code-reader/id308650613?mt=8\">QR Code Reader</a> on your smartphone. Here is how the QR magic happens:
<ol>
<li>Go to the <a href=\"http://bit.ly/\">Bit.ly</a> Website.</li>
<li>Type in the name of the domain you wish to make into a code</li>
<li>Click the copy button that pops out near the short bit.ly link</li>
<li>Paste the copied link in your browser</li>
<li>Add .qr to the end of the link and hit enter</li>
</ol>
I have been pondering what to do with this new tool. The great thing about these codes is that they are a bit of a mystery until scanned. If I were to see this code on a striking advertisement, I would scan it just out of curiosity. I was thinking it would be fun to print them on sticky notes and obnoxiously stick them everywhere. What are your ideas?
',
    'teaser' => '<img src=\"/files/users/2418/leveltenqr2.PNG\" width=\"244\" height=\"248\" alt=\"leveltenqr2.PNG\" />
I am super stoked about being able to create QR codes for my website. To scan the code you must have a <a href=\"http://itunes.apple.com/us/app/quickmark-qr-code-reader/id308650613?mt=8\">QR Code Reader</a> on your smartphone. Here is how the QR magic happens:
<ol>
<li>Go to the <a href=\"http://bit.ly/\">Bit.ly</a> Website.</li>
<li>Type in the name of the domain you wish to make into a code</li>
<li>Click the copy button that pops out near the short bit.ly link</li>
',
    'log' => '',
    'revision_timestamp' => '1287661756',
    'format' => '1',
    'name' => 'admin',
    'picture' => '',
    'data' => 'a:0:{}',
    'path' => 'blog/how-create-qr-code-your-website-5-simple-steps',
    'last_comment_timestamp' => '1287661473',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(
      'tags' => array(
        '1' => 'mobile marketing, QR code, website',
      ),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
  array(
    'nid' => '10',
    'type' => 'blog',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1287661577',
    'changed' => '1287661577',
    'comment' => '2',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '10',
    'revision_uid' => '1',
    'title' => 'Create Smarter Content with Alchemy for Drupal',
    'body' => 'The Alchemy Drupal module integrates the <a href=\"http://www.alchemyapi.com/\">Alchemy advanced content analysis API</a> into Drupal. With this module you can extract high-quality keywords, entities, and concepts from standard node content. This data can be used with the <a href=\"http://drupal.org/project/contentanalysis\">Content Analysis</a>, <a href=\"http://drupal.org/project/autotagging\">Auto Tagging</a>, and <a href=\"http://drupal.org/project/tagging\">Tagging</a> modules to enable fast and intelligent node tagging. Used in conjunction with the Content Analysis suite, the Alchemy module can help improve your site\'s <a href=\"http://www.leveltendesign.com/wiki/seo\">SEO</a>.

<object style=\"height: 390px; width: 640px\"><param name=\"movie\" value=\"http://www.youtube.com/v/iCJv1kzW5Es?version=3\"><param name=\"allowFullScreen\" value=\"true\"><param name=\"allowScriptAccess\" value=\"always\"><embed src=\"http://www.youtube.com/v/iCJv1kzW5Es?version=3\" type=\"application/x-shockwave-flash\" allowfullscreen=\"true\" allowScriptAccess=\"always\" width=\"640\" height=\"390\"></object>

Alchemy does several things, but this module currently concentrates on Alchemy\'s term extraction tools:

<ul>
<li><strong>Keywords:</strong> This tool extracts keywords from node and page content and provides high-quality keywords that are useful for SEO.</li>
<li><strong>Entities:</strong> This tool extracts terms related to people, companies, organizations, cities, geographic features, etc.</li>
<li><strong>Concepts:</strong> Similar to keywords, but capable of abstraction and understanding how concepts relate and tagging accordingly. E.g. \"Hillary Clinton + Michelle Obama + Laura Bush\" == \"First Ladies of the United States.\"</li>
</ul>

This package interfaces into three tagging related modules:

<ul>
<li><strong><a href=\"http://drupal.org/project/contentanalysis\">Content Analysis</a></strong>
Allows you to analyze nodes, urls and freeform content and displays terms. Can be used in conjunctions with <a href=\"http://drupal.org/project/kwresearch\">Keyword Research</a> to tag nodes and build lists of targeted site keywords.</li>
<li><strong><a href=\"http://drupal.org/project/autotagging\">Auto Tagging</a></strong>
Automatically tags nodes with keywords from Alchemy when nodes are submitted. Great for the effort challenged.</li>
<li><strong><a href=\"http://drupal.org/project/tagging\">Tagging</a></strong>
Provides a cool JavaScript interface for adding tags to nodes. The included Alchemy Tagging sub-module allow you to use terms extracted by Alchemy in Tagging\'s list of suggested terms that can be added to the node with a single click.</li></ul>

While the main Alchemy module does not depend on any other module, you will want to interface with at least one of the three modules listed above or you will need to program your own interface.

<a href=\"http://drupal.org/project/alchemy\">Download the Drupal Alchemy module</a> and start putting your content up front.

Alchemy has other tools, but quite frankly, we\'re not sure the best way to use them. So, for now the module is primarily an advanced term extractor. If you have ideas on how to use Alchemy\'s other tools, we\'d love to hear them. Leave a comment and let\'s talk about it. If we get some feature requests, another version is not out of the question.

<a href=\"http://www.flickr.com/photos/cambodia4kidsorg/260004685/\">Image Credit</a>',
    'teaser' => 'The Alchemy Drupal module integrates the <a href=\"http://www.alchemyapi.com/\">Alchemy advanced content analysis API</a> into Drupal. With this module you can extract high-quality keywords, entities, and concepts from standard node content. This data can be used with the <a href=\"http://drupal.org/project/contentanalysis\">Content Analysis</a>, <a href=\"http://drupal.org/project/autotagging\">Auto Tagging</a>, and <a href=\"http://drupal.org/project/tagging\">Tagging</a> modules to enable fast and intelligent node tagging.',
    'log' => '',
    'revision_timestamp' => '1287661577',
    'format' => '1',
    'name' => 'admin',
    'picture' => '',
    'data' => 'a:0:{}',
    'path' => 'blog/create-smarter-content-alchemy-drupal',
    'last_comment_timestamp' => '1287661577',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(
      'tags' => array(
        '1' => 'drupal, drupal module, drupal seo, level ten design, LevelTen Essentials, modules, SEO',
      ),
    ),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)