<?php
/**
 * @file
 * Code for the OpenEnterprise Content feature.
 */

include_once('enterprise_content.features.inc');

/**
 * Implements hook_menu_alter().
 */
function enterprise_content_menu_alter(&$items) {
  $items['node']['page callback'] = 'drupal_goto';
  $items['node']['page arguments'] = array('home');
}

/**
 * Implements hook_migrate_api().
 */
function enterprise_content_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'OpenEnterpriseNode' => array('class_name' => 'OpenEnterpriseNode'),
      'OpenEnterpriseBlocks' => array('class_name' => 'OpenEnterpriseBlocks'),
      'OpenEnterpriseImageBlocks' => array('class_name' => 'OpenEnterpriseImageBlocks'),
    ),
  );
  return $api;
}
